In [1]:
!python3 -m pip install entsoe-py

Collecting entsoe-py
  Downloading entsoe_py-0.8.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from entsoe-py) (2.32.4)
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from entsoe-py) (2025.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from entsoe-py) (4.13.5)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from entsoe-py) (2.2.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->entsoe-py) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->entsoe-py) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->entsoe-py) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->entsoe-py) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->entsoe-py) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->entsoe-py) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->entsoe-py) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->entsoe-py) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->entsoe-py) (2026.4.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->entsoe-py) (1.17.0)
Downloading entsoe_py-0.8.0-py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 21.1 MB/s eta 0:00:00
Installing collected packages: entsoe-py
Successfully installed entsoe-py-0.8.0

In [4]:
from entsoe import EntsoePandasClient
import pandas as pd

client = EntsoePandasClient(api_key='df0f6e8d-b745-4343-ba18-6f720f6a4f67')

start = pd.Timestamp('20251201', tz='Europe/Brussels')
end = pd.Timestamp('20270101', tz='Europe/Brussels')
country_code = 'BE'  # Belgium
country_code_from = 'FR'  # France
country_code_to = 'DE_LU' # Germany-Luxembourg
type_marketagreement_type = 'A01'
contract_marketagreement_type = "A01"
process_type = 'A51'

# methods that return Pandas Series
query_day_ahead_prices = client.query_day_ahead_prices(country_code, start=start, end=end)
# client.query_net_position(country_code, start=start, end=end, dayahead=True)
#client.query_crossborder_flows(country_code_from, country_code_to, start=start, end=end)
# client.query_scheduled_exchanges(country_code_from, country_code_to, start=start, end=end, dayahead=False)
# client.query_net_transfer_capacity_dayahead(country_code_from, country_code_to, start=start, end=end)
# client.query_net_transfer_capacity_weekahead(country_code_from, country_code_to, start=start, end=end)
# client.query_net_transfer_capacity_monthahead(country_code_from, country_code_to, start=start, end=end)
# client.query_net_transfer_capacity_yearahead(country_code_from, country_code_to, start=start, end=end)
# client.query_intraday_offered_capacity(country_code_from, country_code_to, start=start, end=end, implicit=True)
# client.query_offered_capacity(country_code_from, country_code_to, contract_marketagreement_type, start=start, end=end, implicit=True)
# client.query_aggregate_water_reservoirs_and_hydro_storage(country_code, start=start, end=end)

# # methods that return Pandas DataFrames
# client.query_load(country_code, start=start, end=end)
query_load_forecast = client.query_load_forecast(country_code, start=start, end=end)
# client.query_load_and_forecast(country_code, start=start, end=end)
# client.query_generation_forecast(country_code, start=start, end=end)
# client.query_wind_and_solar_forecast(country_code, start=start, end=end, psr_type=None)
# client.query_intraday_wind_and_solar_forecast(country_code, start=start, end=end, psr_type=None)
# client.query_generation(country_code, start=start, end=end, psr_type=None)
# client.query_generation_per_plant(country_code, start=start, end=end, psr_type=None, include_eic=False)
# client.query_installed_generation_capacity(country_code, start=start, end=end, psr_type=None)
# client.query_installed_generation_capacity_per_unit(country_code, start=start, end=end, psr_type=None)
# client.query_imbalance_prices(country_code, start=start, end=end, psr_type=None)
# client.query_contracted_reserve_prices(country_code, type_marketagreement_type, start=start, end=end, psr_type=None)
# client.query_contracted_reserve_amount(country_code, type_marketagreement_type, start=start, end=end, psr_type=None)
# client.query_unavailability_of_generation_units(country_code, start=start, end=end, docstatus=None, periodstartupdate=None, periodendupdate=None)
# client.query_unavailability_of_production_units(country_code, start, end, docstatus=None, periodstartupdate=None, periodendupdate=None)
# client.query_unavailability_transmission(country_code_from, country_code_to, start=start, end=end, docstatus=None, periodstartupdate=None, periodendupdate=None)
# client.query_withdrawn_unavailability_of_generation_units(country_code, start, end)
# client.query_unavailability_of_offshore_grid(area_code, start, end)
# client.query_physical_crossborder_allborders(country_code, start, end, export=True)
# client.query_generation_import(country_code, start, end)
# client.query_procured_balancing_capacity(country_code, process_type, start=start, end=end, type_marketagreement_type=None)

In [5]:
query_day_ahead_prices

2025-12-01 00:00:00+01:00     90.43
2025-12-01 00:15:00+01:00     90.00
2025-12-01 00:30:00+01:00     84.35
2025-12-01 00:45:00+01:00     78.33
2025-12-01 01:00:00+01:00     88.96
                              ...
2026-05-22 22:45:00+02:00    130.30
2026-05-22 23:00:00+02:00    143.69
2026-05-22 23:15:00+02:00    136.73
2026-05-22 23:30:00+02:00    131.47
2026-05-22 23:45:00+02:00    122.39
Length: 16604, dtype: float64

In [ ]:

query_load_forecast

                           Forecasted Load
2024-12-01 00:00:00+01:00           8700.0
2024-12-01 00:15:00+01:00           8569.0
2024-12-01 00:30:00+01:00           8527.0
2024-12-01 00:45:00+01:00           8379.0
2024-12-01 01:00:00+01:00           8291.0
...                                    ...
2024-12-31 22:45:00+01:00           9060.0
2024-12-31 23:00:00+01:00           9082.0
2024-12-31 23:15:00+01:00           8979.0
2024-12-31 23:30:00+01:00           8892.0
2024-12-31 23:45:00+01:00           8780.0

[2976 rows x 1 columns]